apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.keycloak.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.keycloak.port8080 }}
  selector:
    app: keycloak
  type: ClusterIP
