apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloak.secretName }}
  namespace:  {{ .Release.Namespace }}
data:
  KEYCLOAK_ADMIN:  {{ .Files.Get "secrets/keycloak-admin.txt" | b64enc | quote }}
  KEYCLOAK_ADMIN_PASSWORD:   {{ .Files.Get "secrets/keycloak-admin-password.txt" | b64enc | quote }}
type: {{ .Values.secrets.type }}
