apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secretName }}
  namespace: {{ .Release.Namespace }}
data:
  POSTGRES_DB: {{ .Files.Get "secrets/postgres-db.txt" | b64enc | quote }}
  POSTGRES_USER: {{ .Files.Get "secrets/postgres-user.txt" | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Files.Get "secrets/postgres-password.txt" | b64enc | quote }}
type: {{ .Values.secrets.type }}