apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.serviceName }}
  namespace:  {{ .Release.Namespace }}
  labels:
    app: postgres
spec:
  ports:
    - name: pgql
      protocol: TCP
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.targetPort }}
  selector:
    app: postgres
  type: ClusterIP